_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "output/baseline/coco12/model_best_distill.pth" #detectron2://ImageNetPretrained/MSRA/R-50.pkl
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy"
    NUM_CLASSES: 12
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 600
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.0001
DATALOADER:
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: 'dataseed/distill/coco_1_to_exdark_5.txt'
DATASETS:
  CROSS_DATASET: False
  TRAIN: ('coco12_train_1%_source','exdark12_train_5%_target')
  TEST: ('coco12_val', 'exdark12_val')
SEMISUPNET:
  Trainer: "distill"
  BBOX_THRESHOLD: 0.7
  UNSUP_LOSS_WEIGHT: 2.0
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "COCOeval"