_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "R-50.pkl" #detectron2://ImageNetPretrained/MSRA/R-50.pkl
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 13
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960)
  MIN_SIZE_TEST: 800
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (59990, 59995)
  MAX_ITER: 60000
  IMS_PER_BATCH: 16
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: 'dataseed/index5/taco_a+taco_b.txt'
DATASETS:
  CROSS_DATASET: False
  TRAIN: ('tacoa_train', 'tacob_train')
  TEST: ('tacoa_test', )
SEMISUPNET:
  Trainer: "baseline"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 60000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "COCOeval"
